// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentasParcial.Data;

#nullable disable

namespace VentasParcial.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VentasParcial.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MarcaId")
                        .HasName("PK_Marca");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("VentasParcial.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehiculoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<int?>("Cantidad_De_Puertas")
                        .HasColumnType("int");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("MarcaID");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehiculoId")
                        .HasName("PK_Vehiculo");

                    b.HasIndex("MarcaId");

                    b.ToTable("Vehiculo", (string)null);
                });

            modelBuilder.Entity("VentasParcial.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<double>("TotalVentas")
                        .HasColumnType("float");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VehiculoID");

                    b.HasKey("VentaId")
                        .HasName("PK_Venta");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("VentasParcial.Models.Vehiculo", b =>
                {
                    b.HasOne("VentasParcial.Models.Marca", "Marca")
                        .WithMany("Vehiculos")
                        .HasForeignKey("MarcaId")
                        .HasConstraintName("FK_Vehiculo_Marca");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("VentasParcial.Models.Venta", b =>
                {
                    b.HasOne("VentasParcial.Models.Vehiculo", "Vehiculo")
                        .WithMany("Venta")
                        .HasForeignKey("VehiculoId")
                        .HasConstraintName("FK_Venta_Vehiculo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("VentasParcial.Models.Marca", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("VentasParcial.Models.Vehiculo", b =>
                {
                    b.Navigation("Venta");
                });
#pragma warning restore 612, 618
        }
    }
}
